---
- hosts: all
  become: true
  tasks:

  - name: Install the latest python3 and pip3 in Ubuntu
    apt:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install the latest python3 and pip3 in CentOS
    dnf:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: use pip3 as default pip
    shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

  - name: Use python3 as default python
    shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10

  - name: Installing OpenJDK in Ubuntu
    apt:
      name: openjdk-11-jdk
      state: latest
      update_cache: yes
      force_apt_get: true
    when: ansible_distribution == "Ubuntu"

  - name: Installing OpenJDK in CentOS
    dnf:
      name: java-11-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Message of the Day
    copy:
      content: "Ansible Managed node by {{ myusername }}"
      dest: /etc/motd

  - name: User with a variable defined
    copy:
      content: "Ansible Managed node by {{ myusername }}"
      dest: /etc/motd

  - debug:
      var: myusername
